---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: update repository index (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "CentOS"

- hosts: nagios_Ubuntu
  become: true
  roles:
    - nagios_Ubuntu

- hosts: nagios_CentOS
  become: true
  roles:
    - nagios_CentOS
